# DJClaw — your local config.
#
# Generated by `djclaw setup`. Re-run that command (or edit this file by
# hand) any time. Re-running install.sh will NOT touch this file.
#
# Secrets (API keys etc.) live in ~/.config/djclaw/secrets.env, not here.

mixxx:
  url: http://localhost:7778
  timeout: 5
  auto_start: true
  binary: "{mixxx_binary}"
  resource_path: "{mixxx_resource_path}"
  settings_path: "{mixxx_settings_path}"

llm:
  # Model name as registered in litellm.yaml (under model_list[].model_name).
  # Change here AND in litellm.yaml if you want to swap providers.
  model: {llm_model}
  api_base: http://localhost:4000
  temperature: 0.7
  timeout: 30

library:
  music_dir: "{music_dir}"

set:
  default_mood: "{default_mood}"

planner:
  replan_every_n_tracks: 2

knowledge:
  enabled: false   # flip to true once you've populated a LanceDB; v1 ships off

producer:
  enabled: false   # Lyria 3 music generation; needs Vertex/Gemini Enterprise

evolution:
  enabled: false   # self-modification; opt-in

relay:
  enabled: false   # only when self-hosting a public dj.treta.life-style stream

sources:
  youtube: true
  treta_originals: false

daemon:
  heartbeat_interval_seconds: 30
  poll_hz: 2
