# LiteLLM proxy config — generated by `djclaw setup`.
#
# DJClaw's agent talks to a local LiteLLM proxy on port 4000. The proxy
# fans out to whichever provider you configured below. Re-running
# install.sh will NOT touch this file.
#
# To switch providers later: uncomment a different model_list block,
# update model_name to match `llm.model` in config.yaml, and
# `djclaw restart`.

model_list:
{active_block}

{commented_blocks}

litellm_settings:
  drop_params: true
  set_verbose: false
