# DJClaw — secrets. chmod 600.
#
# Generated by `djclaw setup`. Edit by hand to rotate keys; re-running
# install.sh will NOT touch this file.
#
# Do NOT commit this file anywhere.

# ─── LLM provider key ────────────────────────────────────────────────
# This is the key DJClaw uses to authenticate to the LLM provider you
# picked during setup ({provider_label}).
DJTRETA_LLM_API_KEY={llm_api_key}

# ─── Provider-specific (filled in only for the provider you chose) ───
{provider_specific_lines}

# ─── Optional ────────────────────────────────────────────────────────
# Remote-TUI token (only needed if you self-host a public daemon and
# want `djclaw --remote` against it).
# DJTRETA_REMOTE_TOKEN=

# HuggingFace token (only needed if you want to pull the
# NaturNestAI/electronic-music-knowledge dataset for v9 RAG).
# HF_TOKEN=
