model_list:
  - model_name: gemini-3-flash
    litellm_params:
      model: vertex_ai/gemini-2.0-flash
      vertex_project: fandorab2w3
      vertex_location: us-central1

  - model_name: gemini-3.1-pro
    litellm_params:
      model: vertex_ai/gemini-2.5-pro
      vertex_project: fandorab2w3
      vertex_location: us-central1

  - model_name: gemini-3-flash-25
    litellm_params:
      model: vertex_ai/gemini-2.5-flash
      vertex_project: fandorab2w3
      vertex_location: us-central1

  - model_name: gemini-3-flash-preview
    litellm_params:
      model: vertex_ai/gemini-3-flash-preview
      vertex_project: fandorab2w3
      vertex_location: global

  - model_name: gemma-4
    litellm_params:
      model: vertex_ai_beta/gemma-4-26b-a4b-it-maas
      vertex_project: fandorab2w3
      vertex_location: global
      base_model: gemini

general_settings:
  master_key: sk-litellm-vertex-serra-2026
